### ISSUE TITLE
Swift support 

### ISSUE THREAD

**Issue by fidmor89** [CodingFriends/Tincta#15]
Swift is not supported.

**Comment by sameeraleola** [comment]
What fidmor89 said!

**Comment by andre0707** [comment]
Is there a plan to support syntax colouring for swift?

**Comment by jpeinelt** [comment]
As soon as I find time to create a syntax definition file I'll do it. I'm missing it too, just didn't had the time yet.

**Comment by jpeinelt** [comment]
Fixed with next release
#22
