### ISSUE TITLE
find and replace bar while using system dark mode

### ISSUE THREAD

**Issue by andre0707** [CodingFriends/Tincta#20]
when I use the system dark mode, the search and replace bar is not adapting the colours right which makes it really hard to read anything written in there.
(Tincta Version 3.2.0 (3200) downloaded via AppStore)

**Comment by greimers** [comment]
Dark Mode is generally not supported at the moment.
I'll try to make it work.

**Comment by greimers** [comment]
Fixed for next release
#21
