### ISSUE TITLE
Moving the cursor

### ISSUE THREAD

**Issue by rovf** [CodingFriends/Tincta#27]
I think the general problem is that there is no user manual or online help for Tincta (Help/Go to website yields an error 404), but my concrete question is: Is there a shortcut key which would allow me to move the cursor to the beginning or ending of the line? Currently, I have to place it using the mouse or repeatedly press the left/right arrow key, both not being very convenient.

**Comment by greimers** [comment]
The link to the support will be fixed #31 

Tincta supports the standard macOS cursor control commands that are available in all native apps. (This is one reason why macOS is so much better than Windows 😉) To go to the beginning of a line you can press `cmd`+`←` and to the end you go with `cmd`+`→`
macOS (and Tincta) also supports the emacs commands. You find a full list here: http://www.hcs.harvard.edu/~jrus/Site/System%20Bindings.html
