### ISSUE TITLE
Crash on shift+tab

### ISSUE THREAD

**Issue by benbroadaway** [CodingFriends/Tincta#28]
When moving indentation for a line with tab (add indentation) or shift+tab (remove indentation), Tincta will crash if the line is empty.

How to replicate: With a document open in Tincta, press shift+tab on an empty line
Expected behavior: Indentation should remain the same (none) and application should not crash.

Example recording. Tab right twice, shift+tab three times.
![Untitled](https://user-images.githubusercontent.com/4554569/73757209-8396fe80-472e-11ea-9f57-fb56af822ed4.gif)

**Comment by greimers** [comment]
Thanks for pointing this out. The video is very helpful.
I can reproduce this and also notice that there is some more general issue with indenting an empty line.

**Comment by greimers** [comment]
Fixed in v4.0.1
