### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by qylixin** [CodingFriends/Tincta#38]
Hope tincta could support opening files from the terminal

**Comment by greimers** [comment]
While there is not dedicated Tincta command line tool, yet, you can already open files from the terminal with Tincta using the following command:

`open file.txt -a tincta`

**Comment by qylixin** [comment]
> While there is not dedicated Tincta command line tool, yet, you can already open files from the terminal with Tincta using the following command:
> 
> `open file.txt -a tincta`

ok
