### ISSUE TITLE
OK on Big Sur?

### ISSUE THREAD

**Issue by chowardart** [CodingFriends/Tincta#40]
Not really an issue, or at least yet..
Im still waiting for other softwares to make Big Sur compatible versions, but I have no info on Tincta; has anyone tested it on Big Sur?

**Comment by greimers** [comment]
It's running fine. However, there there is an issue that some toolbar icons don't display correctly on Big Sur.

Also, as we don't have many dependencies and Tincta is fully native, compiling it for Apple Silicon should be straight forward.
I think we can provide an update soon.

**Comment by greimers** [comment]
Fixed with next release.

**Comment by chowardart** [comment]
Great! Thank you!...

Wm. Chris Howard

chrisnlcc@me.com
chrisnlcc@outlook.com
chrishoward@chowardart.com

Ex.33:15
Phil. 2:5-11

On Nov 19, 2020, at 11:50 AM, Gabriel Reimers <notifications@github.com> wrote:

﻿
Fixed with next release.

**Comment by greimers** [comment]
v4.1 is available on the App Store now: https://apps.apple.com/app/tincta/id448340648

**Comment by chowardart** [comment]
Ah! Thank you!...

Wm. Chris Howard

chrisnlcc@me.com
chrisnlcc@outlook.com
chrishoward@chowardart.com

Ex.33:15
Phil. 2:5-11

On Nov 23, 2020, at 2:50 AM, Gabriel Reimers <notifications@github.com> wrote:

﻿
v4.1 is available on the App Store now: https://apps.apple.com/app/tincta/id448340648
