### ISSUE TITLE
Tincta malfunctions on Big Sur

### ISSUE THREAD

**Issue by Docwrite** [CodingFriends/Tincta#43]
After downloading Big Sur on my Mac, Tincta fails to fully open. I get a basic text editing-type screen. The icons are small squares with question marks in the center. Is Tincta now compatible with Big Sur?

**Comment by greimers** [comment]
This is fixed with the next update (v4.1) which is already in review for the App Store release.

**Comment by greimers** [comment]
v4.1 is available on the App Store now: https://apps.apple.com/app/tincta/id448340648

**Comment by Docwrite** [comment]
Sorry, but the fixes didn’t work on Big Sur. Now all the icons are gone, rendering the software totally useless.

**Comment by Docwrite** [comment]
Whoops. Spoke too soon. Your fix works. Thanks.

**Comment by greimers** [comment]
😄 Alright. Good to hear that it works!
