### ISSUE TITLE
Autocomplete Quotations is always on

### ISSUE THREAD

**Issue by msypes** [CodingFriends/Tincta#45]
Whether or not the Preferences check box for Autocomplete Quotations is checked or not, typing a single or double quote always creates two such glyphs with the cursor in the middle. My expectation is that with the box unchecked, only a single glyph should be produced.

**Comment by greimers** [comment]
I really can't reproduce this. I also have the autocomplete for quotation always turned off and it works fine.

Maybe its an issue of caching the settings in the system. Have you tried restarting your Mac?
If it persists, can you give more info about your system configuration (espiecially Tincta and macOS version and system language)

**Comment by msypes** [comment]
A caching issues wouldn't surprise me. (If this were a common problem/real bug, I'd expect it to have been caught already.) I restarted my Mac, but it persists. (The machine restarts itself dues to unknown issues at least once a week any way. It's old, and probably on its way out.)
This is a 13" Retina MacBook Pro, late 2013 model running Mojave (10.14.6), English I presume (I'm in the U.S.) Tincta Version 4.1 (4102)

**Comment by scottmetro** [comment]
I am also having the same issue. Autocomplete quotations is always on - iMac 2015 running Big Sur.

**Comment by greimers** [comment]
@scottmetro & @msypes 
Can you try executing `defaults write com.mrFridge.Tincta autocompleteQuotations 0` on the Terminal and then restart Tincta?

**Comment by scottmetro** [comment]
Unfortunately, it didn't work.

**Comment by msypes** [comment]
Didn't work for me either. In fact, I'm seeing this behavior on two machines:

1. 13" Retina MacBook Pro, late 2013 model running Mojave (10.14.6), English I presume (I'm in the U.S.) Tincta Version 4.1 (4102) [This is original machine I noted.]
2. 16" MacBook Pro, 2019 model Catalina (10.15.7), also English
