### ISSUE TITLE
Not a Native M1 app yet?

### ISSUE THREAD

**Issue by SoOlditHurts** [CodingFriends/Tincta#47]
4.1 is shown in the App Store as having native support for the Apple M1. However it is still showing as an Intel-based app within the System info. 
![image](https://user-images.githubusercontent.com/83684120/117092010-aeea0e00-ad22-11eb-95bb-b37375281922.png)

**Comment by greimers** [comment]
Yes it's a bit weird. We compiled it with M1 support but something apparently didn't work correctly. And at that time we didn't have a M1 Mac to test it.
We'll issue an update soon.

**Comment by SoOlditHurts** [comment]
I can test it for you if needed.

**Comment by zazula** [comment]
I can confirm, Intel on M1 mac
