### ISSUE TITLE
"Open In Browser" Command & Toolbar does not function

### ISSUE THREAD

**Issue by chowardart** [CodingFriends/Tincta#50]
Greetings!
I wanted to tweak some HTML code, which opens just fine AND the color coding works perfectly, but I can't get it to open in my browser(s)...

Haven't used in a long time, still thinks its a bad ass app!...

iMac (Retina 5K, 27-inch, 2019) 16 GB RAM OS BigSur 11.2.3
Tincta 4.1 (4102)

**Comment by greimers** [comment]
We could not reproduce this yet. Please note that the open-in-browser feature only works if the file has been saved with .html extension.
