### ISSUE TITLE
Memory leak after opening a big JSON

### ISSUE THREAD

**Issue by VadimMuhtarov** [CodingFriends/Tincta#63]
After opening a 6MB JSON file Tincta starts to leak memory like crazy (>40GB out of 8 physical). I didn't checked with disabled syntax highlighting, but even with it this is not normal.   

MPB, i5, 8GB, Catalina 10.15.7, Tincta 4.2.1 
![Screenshot 2022-01-28 at 09 56 03](https://user-images.githubusercontent.com/17072773/151515403-6f3c8787-d198-43b4-bbcc-074489303bf3.png)
[example.json.zip](https://github.com/CodingFriends/Tincta/files/7957103/example.json.zip)

**Comment by greimers** [comment]
Thanks for reporting this.
However, I think this is a system issue. macOS Catalina and Monterey have had quite a few weird memory leaks.

Anyway, Tincta is not a good choice to open such large files. I think the limit is somewhere between 1-3 MB.
When you have very large files like database dumps or exports, I'd recommend a text editor that is optimized for performance like Vim or Visual Studio.  I even see XCode regularly struggle with large JSON or XML files.
